### ISSUE TITLE
keyword arguments cause a NoneType is not subscriptable error

### ISSUE THREAD

**Issue by sam-stromswold** [XanaduAI/pennylane#234]
I seem to be running into issues with the use of keyword arguments. I've recreated the problem using the small code snippet below:
```
import pennylane as qml
from pennylane import numpy as np
import math

N_qubits = 4
dev1 = qml.device('default.qubit', wires=N_qubits)

@qml.qnode(dev1)
def circuit(params, N=None):
    N_wires = N.val
    for i in range(N_wires):
        qml.RX(params[i], wires=i)
    return [qml.expval.PauliZ(wires=i) for i in range(N_wires)]

res = circuit([math.pi*i/(N_qubits - 1) for i in range(N_qubits)], N=N_qubits)
print(res)
```
which produces the following error:
```
Traceback (most recent call last):
  File "rotations.py", line 16, in <module>
    res = circuit(params, N=N_qubits)
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/pennylane/decorator.py", line 153, in wrapper
    return qnode(*args, **kwargs)
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/pennylane/qnode.py", line 457, in __call__
    return self.evaluate(args, **kwargs)  # args as one tuple
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/pennylane/qnode.py", line 471, in evaluate
    self.construct(args, **kwargs)
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/pennylane/qnode.py", line 298, in construct
    res = self.func(*variables, **kwarg_variables)
  File "rotations.py", line 10, in circuit
    N_wires = N.val
  File "/home/samantha/.local/share/virtualenvs/qaoa-D80nvxhz/lib/python3.7/site-packages/pennylane/variable.py", line 140, in val
    if isinstance(self.kwarg_values[self.name], (Sequence, np.ndarray)):
TypeError: 'NoneType' object is not subscriptable
```
However, when I tweak the program to use the global variable by changing line 10 to,
```
N_wires = N_qubits
```
I get the correct result:
```
[ 1.   0.5 -0.5 -1. ]
```
I did some digging into the backtrace of the thrown error, and I think I suspect that the issue is arising in the construct function of qnode.py. It seems that the Variable object is created by the decorator, but the kwarg_values attribute is empty.

**Comment by josh146** [comment]
Hi @sam-stromswold! Thanks for the bug report. This is currently fixed in pull request #209; until it's merged into master, you can install this PennyLane branch directly:

```
git clone https://github.com/xanaduai/pennylane
cd pennylane && git checkout variables_during_construction
pip install -e .
```

Let me know if that fixes the issue!

**Comment by sam-stromswold** [comment]
Thanks, that seemed to fix it!

**Comment by josh146** [comment]
Awesome :slightly_smiling_face: I'll leave this issue open until the PR mentioned above is merged in

**Comment by josh146** [comment]
#209 is now merged.
